# Here you can define all your data sets by using simple YAML syntax.
#
# Documentation for this file format can be found in "The Data Catalog"
# Link: https://kedro.readthedocs.io/en/stable/data/data_catalog.html
mtg_json:
    type: mtg_predictor.extras.datasets.json_xz_dataset.JsonXzDataSet
    filepath: data/01_raw/AtomicCards.json.xz

atomic_cards_json@json:
    type: mtg_predictor.extras.datasets.json_xz_dataset.JsonXzDataSet
    filepath: data/02_intermediate/AtomicCards.json.xz

atomic_cards_json@pandas:
    type: pandas.JSONDataSet
    filepath: data/02_intermediate/AtomicCards.json.xz
    load_args:
        orient: index

atomic_cards:
    type: pandas.ParquetDataSet
    filepath: data/03_primary/atomic_cards.parquet

vectoriser:
    type: pickle.PickleDataSet
    filepath: data/05_model_input/vectoriser.pickle

selector:
    type: pickle.PickleDataSet
    filepath: data/05_model_input/selector.pickle

classifier:
    type: pickle.PickleDataSet
    filepath: data/05_model_input/classifier.pickle

pipeline:
    type: pickle.PickleDataSet
    filepath: data/05_model_input/pipeline.pickle

pipeline_fitted:
    type: pickle.PickleDataSet
    filepath: data/06_models/pipeline_fitted.pickle

predictions:
    type: pandas.CSVDataSet
    filepath: data/07_model_output/predictions.csv
    load_args:
        index_col: 0
    save_args:
        index: True

confusion_matrix_display:
    type: matplotlib.MatplotlibWriter
    filepath: data/08_reporting/confusion_matrix_display.png
